# Generated by Django 3.1 on 2020-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=10)),
                ('light1_name', models.CharField(max_length=10)),
                ('light1_status', models.CharField(max_length=10)),
                ('light2_name', models.CharField(max_length=10)),
                ('light2_status', models.CharField(max_length=10)),
                ('light3_name', models.CharField(max_length=10)),
                ('light3_status', models.CharField(max_length=10)),
            ],
        ),
    ]
